{% set version = "0.16.4" %}

package:
  name: lief
  version: {{ version }}

source:
  - url: https://github.com/lief-project/LIEF/archive/{{ version }}.tar.gz
    sha256: 311fff5ea9ecbe57b8d02e68739b97673cb14763129ce53af3eac8fee6bf845e

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ccache
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config            # [not win]
    - cmake
    - ninja
  host:
    - nlohmann_json 3.11
    - mbedtls 3.5

outputs:
  - name: py-lief
    script: install-py-lief.sh  # [unix]
    script: install-py-lief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('py-lief', max_pin='x.x') }}
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config            # [not win]
        - cmake
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pydantic >=2.8.2                       # [build_platform != target_platform]
        - scikit-build-core >=0.9.8              # [build_platform != target_platform]
        - setuptools >=70.2.0                    # [build_platform != target_platform]
        - tomli >=2.0.1                          # [build_platform != target_platform]
      host:
        - nlohmann_json 3.11
        - nanobind 2.5.0
        # Dynamically linked to libLIEF for now; see comment in patch section.
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
        - pip
        # Upstream pins build dependencies exactly; we are a bit more lenient
        # here to avoid potential solvability issues.
        - pydantic >=2.8.2
        - scikit-build-core >=0.9.8
        - setuptools >=70.2.0 # [unix]
        # Required for msvc.msvc14_get_vc_env
        - setuptools <=74  # [win]
        - tomli >=2.0.1
      run:
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
    test:
      requires:
        - {{ compiler('cxx') }}
      imports:
        - lief
      commands:
        # Test general functionality by introspecting inter-subpackage linkage.
        - python -c "import ctypes.util, lief; missing = {name for name in {s.name for s in lief.parse(lief._lief.__file__).imported_functions} - {s.name for s in lief.parse(ctypes.util.find_library('LIEF')).exported_functions} if '4LIEF' in name}; assert not missing, missing"

  - name: liblief
    script: install-liblief.sh  # [unix]
    script: install-liblief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('liblief', max_pin='x.x') }}
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config
        - cmake
        - ninja
      host:
        - nlohmann_json 3.11
        - mbedtls 3.5
    test:
      files:
        - tests
      commands:
        - set -x   # [not win]
        - echo on  # [win]
        - pushd tests
        # Aid uniform tests below: Put current dir bluntly on PATH; alias "findstr"->"grep", "call;"->"true".
        - PATH=".:${PATH}"            # [not win]
        - findstr() { grep "${@}"; }  # [not win]
        - call() { true; }            # [not win]

        - pushd self
        - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug . || exit 1
        - ninja || exit 1
        # FIXME: Actual test disabled on Windows for now; LIEF::Parser::parse does not finish on Windows.
        - test-lief-self || exit 1  # [not win]
        - popd

        - pushd macho
        - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug . || exit 1
        - ninja || exit 1
        # This MachO object has no DynamicSymbolCommand, testing for bug fixed in PR:
        # https://github.com/lief-project/LIEF/pull/262
        # FIXME: Actual test disabled on Windows for now; LIEF::MachO::Parser::parse does not finish on Windows.
        - test-lief-macho macOS-libpython2.7.a-getbuildinfo.o > output.txt || exit 1  # [not win]
        - findstr has_dynamic_symbol_command output.txt && exit 1 || call;
        - popd

        - popd
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja

about:
  home: https://lief.re/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A cross platform library to parse, modify and abstract ELF, PE and MachO formats.
  description: |
    It turns out that many projects need to parse executable formats and they usually re-implement
    their own parser. Moreover these parsers are usually bound to one language.
    LIEF attempts to fill this void.
  dev_url: https://github.com/lief-project/LIEF
  doc_url: https://lief.re/doc/latest/

extra:
  recipe-maintainers:
    - isuruf
    - mbargull
    - msarahan
    - xhochy
    - wolfv
