{% set version = "0.14.1" %}

package:
  name: lief
  version: {{ version }}

source:
  - url: https://github.com/lief-project/LIEF/archive/{{ version }}.tar.gz
    sha256: 92916dcb3178353d863aef4f409186889983c56e025b774741d5316a72ec3a7d
    patches:
      - 0001-Dynamically-link-Python-library-to-libLIEF.patch
      - 0002-Export-symbols-used-by-Python-library-from-libLIEF.patch
      - 0003-Inject-proper-extension-module-suffix-via-env-var.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ccache
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config            # [not win]
    - cmake
    - ninja
  host:
    - nlohmann_json

outputs:
  - name: py-lief
    script: install-py-lief.sh  # [unix]
    script: install-py-lief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('py-lief', max_pin='x.x') }}
      ignore_run_exports:
        - python
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config            # [not win]
        - cmake
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pydantic >=2.4.2                       # [build_platform != target_platform]
        - pydantic-core >=2.10.1                 # [build_platform != target_platform]
        - scikit-build-core >=0.6.0              # [build_platform != target_platform]
        - setuptools >=68.2.2                    # [build_platform != target_platform]
        - tomli >=2.0.1                          # [build_platform != target_platform]
      host:
        - nlohmann_json
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
        - pip
        - pydantic >=2.4.2
        - pydantic-core >=2.10.1
        - scikit-build-core >=0.6.0
        - setuptools >=68.2.2
        - tomli >=2.0.1
      run:
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
    test:
      requires:
        - {{ compiler('cxx') }}
      imports:
        - lief
      commands:
        - python -c "import ctypes.util, lief; missing = {name for name in {s.name for s in lief.parse(lief._lief.__file__).imported_functions} - {s.name for s in lief.parse(ctypes.util.find_library('LIEF')).exported_functions} if '4LIEF' in name}; assert not missing, missing"

  - name: liblief
    script: install-liblief.sh  # [unix]
    script: install-liblief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('liblief', max_pin='x.x') }}
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config            # [not win]
        - cmake
        - ninja
      host:
        - nlohmann_json
    test:
      files:
        - tests
      script: run_test_liblief.sh
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja

about:
  home: https://lief.quarkslab.com/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A cross platform library to parse, modify and abstract ELF, PE and MachO formats.
  description: |
    It turns out that many projects need to parse executable formats and they usually re-implement
    their own parser. Moreover these parsers are usually bound to one language.
    LIEF attempts to fill this void.
  doc_url: https://lief.quarkslab.com/doc/stable/index.html
  doc_source_url: https://github.com/lief-project/LIEF/tree/master/doc

extra:
  recipe-maintainers:
    - isuruf
    - mbargull
    - msarahan
    - xhochy
    - wolfv
